# Cursor theme and size enforcement
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# Execute the ctOS greeter in greetd mode
exec-once = CTOS_MODE=greetd quickshell --path /opt/ctos/greeter.qml

animations {
    # Remove launch transitions (hyprland zoom effect)
    enabled = false
}

misc {
    # Hides the hyprland background
    background_color = rgba(0E0E0EFF)
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
