name: 'Monoglow'
preferred_background: 121212

fish_color_normal cccccc
fish_color_command 1bfd9c
fish_color_quote b4b4b4
fish_color_redirection 66b2b2
fish_color_end 7a7a7a
fish_color_error deeeed
fish_color_param cccccc
fish_color_comment 708090
fish_color_match --background=2a2a2a
fish_color_selection --background=2a2a2a
fish_color_search_match --background=2a2a2a
fish_color_history_current --bold
fish_color_operator 1bfd9c
fish_color_escape 66b2b2
fish_color_cwd 1bfd9c
fish_color_cwd_root deeeed
fish_color_valid_path --underline
fish_color_autosuggestion 4a4a4a
fish_color_user 66b2b2
fish_color_host cccccc
fish_color_cancel --reverse
fish_pager_color_prefix cccccc --bold --underline
fish_pager_color_progress f1f1f1 --background=1bfd9c
fish_pager_color_completion cccccc
fish_pager_color_description 708090
fish_pager_color_selected_background --background=2a2a2a
